services:
  postgres1:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - network
    ports:
      - "5432:5432"
      
  postgres2:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db2"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - network
    ports:
      - "5433:5432"
  
  gateway:
    restart: on-failure
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - network
    depends_on:
      - storing-service
      - analytics-service
  
  storing-service:
    restart: on-failure
    build: ./storing
    depends_on:
      postgres1:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres1:5432/db1
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      FILE_STORAGE_PATH: /var/lib/storing-service/uploads
    volumes:
      - /var/lib/analytics-service/upload:/upload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - network
      
  analytics-service:
    restart: on-failure
    build: ./analytics
    depends_on:
      postgres2:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres2:5432/db2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      FILE_STORAGE_PATH: /var/lib/analytics-service/pics
    volumes:
      - /var/lib/analytics-service/pics:/pics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - network

volumes:
  pgdata1:
  pgdata2:

networks:
  network:
