server:
  port: 8080

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://postgres2:5432/db2
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      auto-commit: false
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          provider_disables_autocommit: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    path: /var/lib/analytics-service/pics

logging:
  level:
    root: ERROR
    com.anton.kpo: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.anton.kpo
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
